# Generated by Django 4.2 on 2023-04-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Yapılacaklar')),
                ('creatingDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('deleteDate', models.DateField(auto_now_add=True)),
                ('completedPercent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamamlanma Yüzdesi')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bitirilme Durumu')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.todolist', verbose_name='TO-DO Listesi')),
            ],
            options={
                'verbose_name_plural': 'TO-DO Adımları',
            },
        ),
    ]
