# Generated by Django 4.2 on 2023-04-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todostep',
            old_name='creation_date',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='todostep',
            old_name='delete_date',
            new_name='deleteDate',
        ),
        migrations.RenameField(
            model_name='todostep',
            old_name='is_completed',
            new_name='isCompleted',
        ),
        migrations.RenameField(
            model_name='todostep',
            old_name='todo_list',
            new_name='todoList',
        ),
        migrations.RenameField(
            model_name='todostep',
            old_name='update_date',
            new_name='updateDate',
        ),
    ]
