# Generated by Django 4.2 on 2023-05-01 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_creation_date_todostep_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name_plural': 'To Do Listesi'},
        ),
        migrations.AlterModelOptions(
            name='todostep',
            options={'verbose_name_plural': 'To Do Adımı'},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='type1', max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deleteDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todostep',
            name='deleteDate',
            field=models.DateField(auto_now_add=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='todostep',
            name='todoList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.todolist', verbose_name='To Do Listesi'),
        ),
    ]
